id: P9A3F11A5
initial_creation_type: input
source_metadata:
  title: Viṣṇusmṛti
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Dharma -- Smṛti
  data entry: I. Shima
  contribution to GRETIL: I. Shima
  collation: T. Hayashi
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:29:22.759812'
last_modified_at: '2022-03-09T15:29:22.759828'
